# This file uses the version 2 docker-compose file format, described here:
# https://docs.docker.com/compose/compose-file/#version-2
#

version: '2'

services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      - STORAGE_TYPE=mem
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411

  mongo:
    image: mongo
    ports:
      - 27017:27017

  #prometheus:
    #image: prom/prometheus
    #command:
      #- '--config.file=/mnt/c/Users/aalamino/workspace_demo_eden_oscar/demo-edem/prometheus.yml'
      #- '--storage.tsdb.path=/prometheus'
      #- '--web.console.libraries=/usr/share/prometheus/console_libraries'
      #- '--web.console.templates=/usr/share/prometheus/consoles'
    #ports:
      #- 9090:9090
  grafana:
    image: grafana/grafana
    #depends_on:
      #- prometheus
    ports:
      - 3000:3000
