{
 "title": "Products",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Get all Products",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(get_Products_all_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get all Products Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(get_Product_all_error_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get Product id",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(get_Product_id_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get Product id Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(get_Product_id_error_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}